### PR TITLE
Use client_id in logout request

### PR DESCRIPTION
**Pull request by aduth**
Pairs with (blocked by) https://github.com/18F/identity-idp/pull/7017 (I put together these changes to test that pull request, figured I may as well make a pull request)

### CODE REVIEW

**Review by mitchellhenke — APPROVED** [review]
👍🏼

**Comment by aduth** [comment]
@mitchellhenke Do you have a sense when these changes will be safe to merge? Is the feature flag that's checked in https://github.com/18F/identity-idp/pull/7017 already available in all the environments we're deploying this sample app?

**Comment by mitchellhenke** [comment]
> @mitchellhenke Do you have a sense when these changes will be safe to merge? Is the feature flag that's checked in [18F/identity-idp#7017](https://github.com/18F/identity-idp/pull/7017) already available in all the environments we're deploying this sample app?

It should be enabled in production today, and I opened https://github.com/18F/identity-idp/pull/7052 to enable it everywhere else too.

**Comment by mitchellhenke** [comment]
This is good to go

**Pull request merged**
