### PR TITLE
LG-1422: successful login returns to home page

### PR DESCRIPTION
**Pull request by solipet**
As an agency partner looking at an example app, I want the success page to look like the demo app's main page, so that I do not think the demo site is broken.

Successful login/logout now returns to the home page.

Note: to continue showing the returned userinfo, they will display in an overlay div but, like the flash message, will disappear upon reloading the page.

### CODE REVIEW

**Comment by solipet** [comment]
Do not merge until https://github.com/18F/identity-idp/pull/3149 has been merged -- needs the new redirect uri to be in place first! :-)

**Comment by solipet** [comment]
Before:
Screen Shot 2019-07-30 at 4 52 24 PM

After:
Screen Shot 2019-07-30 at 4 50 24 PM

**Comment by stevegsa** [comment]
THIS LOOKS AMAZING!  Do we want to mask the social?  Looks like the oidc app does that

**Comment by brodygov** [comment]
Looks like it's still using `maybe_redact_ssn()`, which is currently configured to not redact in local dev so that you can be more likely to find bugs there.

**Pull request merged**
