### PR TITLE
Bundle update and default to ruby3

### PR DESCRIPTION
**Pull request by jgrevich**
Bundle update and default to ruby3

### CODE REVIEW

**Comment by jgrevich** [comment]
Good point, I think it does.

**Comment by jgrevich** [comment]
> Good point, I think it does.

I take that back, we didn't have that set in the gemfile before. Perhaps we should if we're doing that with the IdP and other repos https://github.com/18F/identity-idp/blob/main/Gemfile#L4, what do you think?

If I understand correctly it's purpose is to make sure that commands executed with `bundle exec` are run in the specified ruby version in Gemfile in the event that the `.ruby-version` is being ignored or overridden, or is there another reason why we would do that? Personally I don't see the need to be so restrictive if it's compatible with other versions.

**Review by mitchellhenke — APPROVED** [review]
Looks good to me. Did this get tested to make sure it provisions okay?

**Comment by mitchellhenke** [comment]
Oops, just realized this will need to change too: https://github.com/18F/identity-oidc-sinatra/blob/main/.circleci/config.yml#L10

**Comment by jgrevich** [comment]
Good catch with circleci, I updated that and will test a provision now.

**Comment by jgrevich** [comment]
```
App 13043 output: Error: The application encountered the following error: Unable to find a compatible xml library. Ensure that you have installed or added to your Gemfile one of ox, oga, libxml, nokogiri or rexml (RuntimeError)
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/xml/parser.rb:74:in `set_default_engine'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/xml/parser.rb:96:in `<class:Parser>'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/xml/parser.rb:7:in `<module:Xml>'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/xml/parser.rb:5:in `<module:Aws>'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/xml/parser.rb:3:in `<top (required)>'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/xml.rb:8:in `require_relative'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/xml.rb:8:in `<top (required)>'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core.rb:68:in `require_relative'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core.rb:68:in `<top (required)>'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-secretsmanager-1.61.0/lib/aws-sdk-secretsmanager.rb:11:in `require'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/aws-sdk-secretsmanager-1.61.0/lib/aws-sdk-secretsmanager.rb:11:in `<top (required)>'
App 13043 output:     /srv/sp-oidc-sinatra/releases/20220517000042/config.rb:4:in `require'
App 13043 output:     /srv/sp-oidc-sinatra/releases/20220517000042/config.rb:4:in `<top (required)>'
App 13043 output:     /srv/sp-oidc-sinatra/releases/20220517000042/app.rb:17:in `require_relative'
App 13043 output:     /srv/sp-oidc-sinatra/releases/20220517000042/app.rb:17:in `<top (required)>'
App 13043 output:     config.ru:3:in `require'
App 13043 output:     config.ru:3:in `block in <main>'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 13043 output:     /srv/sp-oidc-sinatra/shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 13043 output:     config.ru:1:in `new'
App 13043 output:     config.ru:1:in `<main>'
App 13043 output:     /opt/ruby_build/versions/2.7.5/lib/ruby/gems/2.7.0/gems/passenger-6.0.9/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 13043 output:     /opt/ruby_build/versions/2.7.5/lib/ruby/gems/2.7.0/gems/passenger-6.0.9/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 13043 output:     /opt/ruby_build/versions/2.7.5/lib/ruby/gems/2.7.0/gems/passenger-6.0.9/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 13043 output:     /opt/ruby_build/versions/2.7.5/lib/ruby/gems/2.7.0/gems/passenger-6.0.9/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 13043 output:     /opt/ruby_build/versions/2.7.5/lib/ruby/gems/2.7.0/gems/passenger-6.0.9/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 13043 output:     /opt/ruby_build/versions/2.7.5/lib/ruby/gems/2.7.0/gems/passenger-6.0.9/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 13043 output:     /opt/ruby_build/versions/2.7.5/lib/ruby/gems/2.7.0/gems/passenger-6.0.9/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-05-17 00:02:43.7211 8621/T1q age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /srv/sp-oidc-sinatra/current: The application encountered the following error: Unable to find a compatible xml library. Ensure that you have installed or added to your Gemfile one of ox, oga, libxml, nokogiri or rexml (RuntimeError)
  Error ID: 7a338e9c
  Error details saved to: /tmp/passenger-error-8WjI7b.html

[ E 2022-05-17 00:02:43.7238 8621/Tk age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 7-2] Cannot checkout session because a spawning error occurred. The identifier of the error is 7a338e9c. Please see earlier logs for details about the error.
```

Passenger wants an XML lib in production so I moved `nokogiri` from the `:test` group to the main block of gems in the `Gemfile`.

**Review by mitchellhenke — APPROVED** [review]

**Comment by aduth** [comment]
I think this may have broken default local development, which had previously relied on Webrick to be provided natively through Ruby < 3. Since it isn't as of Ruby 3, and we have no other web server, `make run` fails with...

```
$ make run
bundle exec rackup -p 9292 --host localhost
bundler: failed to load command: rackup (/.rbenv/versions/3.0/bin/rackup)
/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/handler.rb:45:in `pick': Couldn't find handler for: puma, thin, falcon, webrick. (LoadError)
```

**Pull request merged**
